/*
 * Copyright (C) 2026 Nagisa Sekiguchi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cstdio>
#include <vector>

#include <misc/opt.hpp>
#include <unicode/property.h>
#include <unicode/radix_tree.h>

#include "code_pointer_helper.hpp"

using namespace arsh;

struct EMOJI_SEQ_ENTRY {
  ucp::RGIEmojiSeq property;
  CodePointArray codes;
};

using namespace arsh::ucp;

#include "./emoji_seq.in"

static void usage(FILE *fp, char **argv) { fprintf(fp, "usage: %s [output path]\n", argv[0]); }

static void invalidOption(char **argv, int opt) {
  fprintf(stderr, "invalid option: -%c", opt);
  usage(stderr, argv);
}

static int emit(FILE *fp, const char *bin, const FlexBuffer<uint8_t> &buf) {
  fprintf(fp, "/* Auto-generated by %s */\n", bin);
  fputs("#ifndef AUTO_GEN_PACKED_EMOJI_TRIE_H\n", fp);
  fputs("#define AUTO_GEN_PACKED_EMOJI_TRIE_H\n\n", fp);
  fputs("static constexpr uint8_t packed_emoji_radix_tree_table[] = {", fp);
  for (unsigned int i = 0; i < buf.size(); i++) {
    if (i % 16 == 0) {
      fputs("\n    ", fp);
    }
    fprintf(fp, "0x%02X, ", buf[i]);
  }
  fputs("\n};\n\n", fp);
  fputs("#endif //AUTO_GEN_PACKED_EMOJI_TRIE_H\n", fp);
  return 0;
}

static RGIEmojiSeq lookupRGIEmojiSeqFrom(StringRef ref, const uint8_t *const ptr,
                                         const size_t size) {
  return static_cast<RGIEmojiSeq>(PackedRadixTree(ptr, size).find(ref));
}

int main(int argc, char **argv) {
  opt::GetOptState optState("h");
  auto iter = argv + 1;
  const auto end = argv + argc;
  for (int opt; (opt = optState(iter, end)) != -1;) {
    if (opt == 'h') {
      usage(stdout, argv);
      return 2;
    }
    invalidOption(argv, opt);
    return 1;
  }
  if (iter == end) {
    fprintf(stderr, "need output path\n");
    usage(stderr, argv);
    return 1;
  }
  FILE *fp = fopen(*iter, "w");
  if (!fp) {
    perror(*iter);
    return 1;
  }

  std::vector<std::pair<std::string, RGIEmojiSeq>> foldSeq;
  RadixTree tree;
  for (auto [p, codes] : emoji_seq_table) {
    auto str = codes.toUTF8();
    if (!tree.add(str, toUnderlying(p))) {
      fatal("cannot insert emoji seq: %s", str.c_str());
    }
    auto fold = codes.toUTF8CaseFold();
    if (fold != str) {
      if (!tree.add(fold, toUnderlying(p | RGIEmojiSeq::CASE_IGNORE))) {
        fatal("cannot insert emoji seq: %s", str.c_str());
      }
      foldSeq.emplace_back(std::move(fold), p);
    }
  }
  FlexBuffer<uint8_t> buf;
  if (!serialize(tree, buf)) {
    fatal("too large radix tree");
  }
  for (auto [p, codes] : emoji_seq_table) {
    auto str = codes.toUTF8();
    if (lookupRGIEmojiSeqFrom(str, buf.data(), buf.size()) != p) {
      fatal("cannot lookup emoji seq: %s\n", str.c_str());
    }
    auto fold = codes.toUTF8CaseFold();
    if (fold != str) {
      if (lookupRGIEmojiSeqFrom(fold, buf.data(), buf.size()) !=
          (p | ucp::RGIEmojiSeq::CASE_IGNORE)) {
        fatal("cannot lookup emoji seq: %s\n", str.c_str());
      }
    }
  }
  // check fold seq
  if (foldSeq.empty()) {
    fatal("fold emoji seq is not found\n");
  }
  for (auto &[seq, p] : foldSeq) {
    if (lookupRGIEmojiSeqFrom(seq, buf.data(), buf.size()) != (ucp::RGIEmojiSeq::CASE_IGNORE | p)) {
      fatal("not found: %s\n", seq.c_str());
    }
  }
  return emit(fp, argv[0], buf);
}