/*
 * Copyright (C) 2026 Nagisa Sekiguchi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cstdio>
#include <vector>

#include <misc/opt.hpp>
#include <unicode/property.h>
#include <unicode/radix_tree.h>

#include "code_pointer_helper.hpp"

using namespace arsh;

struct EMOJI_SEQ_ENTRY {
  ucp::RGIEmojiSeq property;
  CodePointArray codes;
};

using namespace arsh::ucp;

#include "./emoji_seq.in"

static void usage(FILE *fp, char **argv) { fprintf(fp, "usage: %s [-d] [output path]\n", argv[0]); }

static void invalidOption(char **argv, int opt) {
  fprintf(stderr, "invalid option: -%c", opt);
  usage(stderr, argv);
}

static int emit(FILE *fp, const char *bin, const FlexBuffer<uint8_t> &buf,
                uint16_t longestStringSize) {
  fprintf(fp, "/* Auto-generated by %s */\n", bin);
  fputs("#ifndef AUTO_GEN_PACKED_EMOJI_TRIE_H\n", fp);
  fputs("#define AUTO_GEN_PACKED_EMOJI_TRIE_H\n\n", fp);
  fputs("static constexpr uint8_t packed_emoji_radix_tree_table[] = {", fp);
  for (unsigned int i = 0; i < buf.size(); i++) {
    if (i % 16 == 0) {
      fputs("\n    ", fp);
    }
    fprintf(fp, "0x%02X, ", buf[i]);
  }
  fputs("\n};\n\n", fp);
  fprintf(fp, "constexpr uint16_t longest_packed_emoji_string_size = %d;\n\n", longestStringSize);
  fputs("#endif //AUTO_GEN_PACKED_EMOJI_TRIE_H\n", fp);
  return 0;
}

static std::vector<std::pair<std::string, unsigned char>> collect(const RadixTree &tree) {
  std::vector<std::pair<std::string, unsigned char>> values;
  tree.iterate([&values](StringRef ref, unsigned char p) {
    values.emplace_back(ref.toString(), p);
    return true;
  });
  return values;
}

int main(int argc, char **argv) {
  opt::GetOptState optState("hd");
  auto iter = argv + 1;
  const auto end = argv + argc;
  bool debug = false;
  for (int opt; (opt = optState(iter, end)) != -1;) {
    if (opt == 'd') {
      debug = true;
      continue;
    }
    if (opt == 'h') {
      usage(stdout, argv);
      return 2;
    }
    invalidOption(argv, opt);
    return 1;
  }
  if (iter == end) {
    fprintf(stderr, "need output path\n");
    usage(stderr, argv);
    return 1;
  }
  FILE *fp = fopen(*iter, "w");
  if (!fp) {
    perror(*iter);
    return 1;
  }

  std::vector<std::pair<std::string, RGIEmojiSeq>> foldSeq;
  RadixTree tree;
  size_t maxBytes = 0;
  for (auto [p, codes] : emoji_seq_table) {
    auto str = codes.toUTF8();
    if (debug) {
      fprintf(stdout, "try to insert emoji seq:(%s, %zu)\n", str.c_str(), str.size());
    }
    if (tree.add(str, toUnderlying(p)) != RadixTree::AddStatus::OK) {
      fatal("cannot insert emoji seq: %s\n", str.c_str());
    }
    maxBytes = std::max(maxBytes, str.size());
    auto fold = codes.toUTF8CaseFold();
    if (fold != str) {
      if (debug) {
        fprintf(stdout, "found fold emoji seq, original:(%s, %zu), fold:(%s, %zu)\n", str.c_str(),
                str.size(), fold.c_str(), fold.size());
        fprintf(stdout, "try to insert emoji seq:(%s, %zu)\n", fold.c_str(), fold.size());
      }
      if (tree.add(fold, toUnderlying(p | RGIEmojiSeq::CASE_IGNORE)) != RadixTree::AddStatus::OK) {
        fatal("cannot insert emoji seq: %s\n", str.c_str());
      }
      maxBytes = std::max(maxBytes, fold.size());
      foldSeq.emplace_back(std::move(fold), p);
    }
  }
  FlexBuffer<uint8_t> buf;
  if (!serialize(tree, buf)) {
    fatal("too large radix tree\n");
  }
  if (maxBytes != tree.longestStringSize()) {
    fatal("longestStrigSize mismatched, expected: %zu, actual: %zu\n", maxBytes,
          tree.longestStringSize());
  }
  if (maxBytes >= static_cast<size_t>(UINT16_MAX)) {
    fatal("contains too large string\n");
  }

  // check trie
  const PackedRadixTree emojiTrie(maxBytes, buf.data(), buf.size());
  for (auto [p, codes] : emoji_seq_table) {
    auto str = codes.toUTF8();
    if (emojiTrie.find(str) != toUnderlying(p) ||
        emojiTrie.findLongestMatched(str) !=
            std::make_pair<uint16_t, uint8_t>(str.size(), toUnderlying(p))) {
      fatal("cannot lookup emoji seq: %s\n", str.c_str());
    }
    auto fold = codes.toUTF8CaseFold();
    if (fold != str) {
      if (emojiTrie.find(fold) != toUnderlying(p | RGIEmojiSeq::CASE_IGNORE) ||
          emojiTrie.findLongestMatched(fold) !=
              std::make_pair<uint16_t, uint8_t>(fold.size(),
                                                toUnderlying(p | RGIEmojiSeq::CASE_IGNORE))) {
        fatal("cannot lookup emoji seq: %s\n", str.c_str());
      }
    }
  }
  // check fold seq
  if (foldSeq.empty()) {
    fatal("fold emoji seq is not found\n");
  }
  for (auto &[seq, p] : foldSeq) {
    if (emojiTrie.find(seq) != toUnderlying(RGIEmojiSeq::CASE_IGNORE | p) ||
        emojiTrie.findLongestMatched(seq) !=
            std::make_pair<uint16_t, uint8_t>(seq.size(),
                                              toUnderlying(RGIEmojiSeq::CASE_IGNORE | p))) {
      fatal("not found: %s\n", seq.c_str());
    }
  }

  // check iteration
  auto allEmoji = collect(tree);
  if (auto expectSize = foldSeq.size() + std::size(emoji_seq_table);
      expectSize != allEmoji.size()) {
    fatal("broken emoji list, expect: %zu, actual: %zu\n", expectSize, allEmoji.size());
  }
  for (auto &[s, p] : allEmoji) {
    if (emojiTrie.find(s) != p) {
      fatal("not found: %s\n", s.c_str());
    }
  }
  return emit(fp, argv[0], buf, static_cast<uint16_t>(maxBytes));
}