/*
 * Copyright (C) 2026 Nagisa Sekiguchi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cstdio>
#include <vector>

#include <misc/opt.hpp>

#include "fold_table.h"

using namespace arsh;

static void usage(FILE *fp, char **argv) { fprintf(fp, "usage: %s [-d] [output path]\n", argv[0]); }

static void invalidOption(char **argv, int opt) {
  fprintf(stderr, "invalid option: -%c", opt);
  usage(stderr, argv);
}

static void emit(FILE *fp, const char *bin, const fold::FoldTable &foldTable) {
  fprintf(fp, "/* Auto-generated by %s */\n", bin);
  fputs("#ifndef AUTO_GEN_SIMPLE_CASE_FOLD_TABLE_H\n", fp);
  fputs("#define AUTO_GEN_SIMPLE_CASE_FOLD_TABLE_H\n\n", fp);
  fprintf(fp, "static constexpr unsigned int simple_case_fold_block_shift = %d;\n\n",
          fold::FoldTable::SHIFT);
  fprintf(fp, "static constexpr unsigned int simple_case_fold_block_size = %d;\n\n",
          fold::FoldTable::BLOCK_SIZE);
  fprintf(fp, "static constexpr int max_fold_code_point = %d;\n\n",
          foldTable.getMaxFoldCodePoint());
  fputs("static constexpr uint8_t simple_case_fold_block_indexes[] = {", fp);
  for (unsigned int i = 0; i < foldTable.getBlockIndexes().size(); i++) {
    if (i % 16 == 0) {
      fputs("\n    ", fp);
    }
    fprintf(fp, "0x%02X, ", foldTable.getBlockIndexes()[i]);
  }
  fputs("\n};\n\n", fp);
  fputs("static constexpr uint32_t simple_case_fold_blocks[] = {", fp);
  for (auto &block : foldTable.getBlocks()) {
    for (unsigned int i = 0; i < block.values.size(); i++) {
      if (i % 8 == 0) {
        fputs("\n    ", fp);
      }
      fprintf(fp, "0x%08X, ", block.values[i]);
    }
    fputs("\n", fp);
  }
  fputs("};\n\n", fp);
  fputs("#endif //AUTO_GEN_SIMPLE_CASE_FOLD_TABLE_H\n", fp);
}

int main(int argc, char **argv) {
  opt::GetOptState optState("hd");
  auto iter = argv + 1;
  const auto end = argv + argc;
  bool debug = false;
  for (int opt; (opt = optState(iter, end)) != -1;) {
    if (opt == 'd') {
      debug = true;
      continue;
    }
    if (opt == 'h') {
      usage(stdout, argv);
      return 2;
    }
    invalidOption(argv, opt);
    return 1;
  }
  if (iter == end) {
    fprintf(stderr, "need output path\n");
    usage(stderr, argv);
    return 1;
  }
  FILE *fp = fopen(*iter, "w");
  if (!fp) {
    perror(*iter);
    return 1;
  }
  auto foldTable = fold::FoldTable::create();
  if (debug) {
    fprintf(stderr, "max fold code point: U+%04X\n", foldTable.getMaxFoldCodePoint());
    fprintf(stderr, "size of block index table: %zu\n", foldTable.getBlockIndexes().size());
    fprintf(stderr, "size of block shift: %d\n", fold::FoldTable::SHIFT);
    fprintf(stderr, "size of block: %d\n", fold::FoldTable::BLOCK_SIZE);
    fprintf(stderr, "size of block table: %zu\n", foldTable.getBlocks().size());
    fprintf(stderr, "total bytes: %zu\n",
            foldTable.getBlockIndexes().size() +
                (foldTable.getBlocks().size() * fold::FoldTable::BLOCK_SIZE * 4));
  }
  emit(fp, argv[0], foldTable);
  return 0;
}
