/*
 * Copyright (C) 2026 Nagisa Sekiguchi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <algorithm>
#include <cstdio>
#include <cstring>
#include <set>
#include <string>
#include <vector>

#include "misc/string_ref.hpp"
#include "object_file.h"

namespace {

using namespace arsh;

void printUsage(const char *argv0) {
  fprintf(stderr, "usage: %s --output <path> <stencil.o>...\n", argv0);
}

void writeBytes(FILE *fp, const std::vector<uint8_t> &bytes) {
  for (size_t i = 0; i < bytes.size(); i++) {
    if (i % 12 == 0) {
      fprintf(fp, "\n  ");
    }
    fprintf(fp, "0x%02x,", bytes[i]);
  }
  fprintf(fp, "\n");
}

bool generate(const char *output, const std::vector<std::string> &inputs, const bool debug) {
  gen_stencil::StencilObject object;
  for (const auto &input : inputs) {
    gen_stencil::StencilObject tmp;
    std::string error;
    if (!gen_stencil::parseStencilObject(input, tmp, error)) {
      fprintf(stderr, "failed to parse stencil object %s: %s\n", input.c_str(), error.c_str());
      return false;
    }
    for (auto &fn : tmp.functions) {
      object.functions.push_back(std::move(fn));
    }
    for (auto &pair : tmp.dataSections) {
      if (object.dataSections.count(pair.first)) {
        fprintf(stderr, "duplicated data section: %s\n", pair.first.c_str());
        return false;
      }
      object.dataSections[pair.first] = std::move(pair.second);
    }
  }

  // sort by opcode name for deterministic output
  std::sort(object.functions.begin(), object.functions.end(),
            [](const auto &x, const auto &y) { return x.opcode < y.opcode; });

  std::set<std::string> seen;
  for (const auto &fn : object.functions) {
    if (!seen.insert(fn.opcode).second) {
      fprintf(stderr, "duplicated stencil: stencil_%s\n", fn.opcode.c_str());
      return false;
    }
    if (fn.holes.empty()) {
      fprintf(stderr, "stencil_%s has no patchable hole (unexpected: it cannot continue)\n",
              fn.opcode.c_str());
      return false;
    }
  }

  FILE *fp = fopen(output, "wb");
  if (!fp) {
    fprintf(stderr, "cannot open output: %s\n", output);
    return false;
  }

  fprintf(fp, "// generated by tools/gen_jit_stencil. do not edit.\n");
  fprintf(fp, "#ifndef ARSH_REGEX_JIT_STENCIL_DATA_H\n");
  fprintf(fp, "#define ARSH_REGEX_JIT_STENCIL_DATA_H\n\n");
  fprintf(fp, "#include <cstdint>\n\n");
  fprintf(fp, "namespace arsh::regex::jit {\n\n");

  fprintf(fp, "/**\n");
  fprintf(fp, " * a patch site: %u bytes at `offset` within the stencil code are overwritten with the\n",
          8u);
  fprintf(fp, " * address of `symbol` (plus `addend`). for a section symbol the compiler uses the\n");
  fprintf(fp, " * address of the copied data section instead.\n");
  fprintf(fp, " */\n");
  fprintf(fp, "struct StencilHoleData {\n");
  fprintf(fp, "  uint32_t offset;\n");
  fprintf(fp, "  uint32_t size;\n");
  fprintf(fp, "  const char *symbol;\n");
  fprintf(fp, "  int64_t addend;\n");
  fprintf(fp, "  bool isSection;\n");
  fprintf(fp, "};\n\n");

  fprintf(fp, "struct StencilData {\n");
  fprintf(fp, "  const char *opcode;\n");
  fprintf(fp, "  const uint8_t *code;\n");
  fprintf(fp, "  uint32_t size;\n");
  fprintf(fp, "  const StencilHoleData *holes;\n");
  fprintf(fp, "  uint32_t holeCount;\n");
  fprintf(fp, "};\n\n");

  fprintf(fp, "/** a local constant pool carried into the code buffer. */\n");
  fprintf(fp, "struct StencilDataSectionData {\n");
  fprintf(fp, "  const char *name;\n");
  fprintf(fp, "  const uint8_t *data;\n");
  fprintf(fp, "  uint32_t size;\n");
  fprintf(fp, "  uint32_t alignment;\n");
  fprintf(fp, "};\n\n");

  for (size_t i = 0; i < object.functions.size(); i++) {
    const auto &fn = object.functions[i];
    fprintf(fp, "inline constexpr uint8_t STENCIL_CODE_%zu[] = {", i);
    writeBytes(fp, fn.code);
    fprintf(fp, "};\n");
    fprintf(fp, "inline constexpr StencilHoleData STENCIL_HOLES_%zu[] = {\n", i);
    for (const auto &hole : fn.holes) {
      fprintf(fp, "    {%u, 8, \"%s\", %lld, %s},\n", hole.offset, hole.symbol.c_str(),
              static_cast<long long>(hole.addend), hole.isSection ? "true" : "false");
    }
    fprintf(fp, "};\n");
  }
  fprintf(fp, "\n");

  if (debug) {
    for (size_t i = 0; i < object.functions.size(); i++) {
      const auto &fn = object.functions[i];
      fprintf(stderr, "stencil_%-18s code=%zu bytes, holes=%zu\n", fn.opcode.c_str(), fn.code.size(),
              fn.holes.size());
    }
  }

  fprintf(fp, "/** all extracted stencils, sorted by opcode name. */\n");
  fprintf(fp, "inline constexpr StencilData STENCILS[] = {\n");
  for (size_t i = 0; i < object.functions.size(); i++) {
    const auto &fn = object.functions[i];
    fprintf(fp, "    {\"%s\", STENCIL_CODE_%zu, %zu, STENCIL_HOLES_%zu, %zu},\n", fn.opcode.c_str(),
            i, fn.code.size(), i, fn.holes.size());
  }
  fprintf(fp, "};\n\n");

  auto dataIter = object.dataSections.begin();
  for (size_t i = 0; i < object.dataSections.size(); i++, ++dataIter) {
    fprintf(fp, "inline constexpr uint8_t STENCIL_DATA_%zu[] = {", i);
    writeBytes(fp, dataIter->second.data);
    fprintf(fp, "};\n");
  }
  if (!object.dataSections.empty()) {
    fprintf(fp, "\n");
  }

  fprintf(fp, "inline constexpr StencilDataSectionData STENCIL_DATA_SECTIONS[] = {\n");
  dataIter = object.dataSections.begin();
  for (size_t i = 0; i < object.dataSections.size(); i++, ++dataIter) {
    fprintf(fp, "    {\"%s\", STENCIL_DATA_%zu, %zu, %u},\n", dataIter->first.c_str(), i,
            dataIter->second.data.size(), dataIter->second.alignment);
  }
  fprintf(fp, "};\n\n");

  fprintf(fp, "} // namespace arsh::regex::jit\n\n");
  fprintf(fp, "#endif // ARSH_REGEX_JIT_STENCIL_DATA_H\n");
  fclose(fp);

  fprintf(stderr, "generated %s: %zu stencils, %zu data sections\n", output, object.functions.size(),
          object.dataSections.size());
  return true;
}

} // namespace

int main(int argc, char **argv) {
  const char *output = nullptr;
  bool debug = false;
  std::vector<std::string> inputs;
  for (int i = 1; i < argc; i++) {
    if (strcmp(argv[i], "--output") == 0 && i + 1 < argc) {
      output = argv[++i];
    } else if (strcmp(argv[i], "--debug") == 0) {
      debug = true;
    } else if (argv[i][0] == '-') {
      printUsage(argv[0]);
      return 1;
    } else {
      inputs.emplace_back(argv[i]);
    }
  }
  if (!output || inputs.empty()) {
    printUsage(argv[0]);
    return 1;
  }
  return generate(output, inputs, debug) ? 0 : 1;
}
