#!/usr/bin/env expect

# set argument

set bin_name [lindex $argv 0]
spawn ${bin_name} --norc -s hello

set CTRLD \004
set timeout 1

expect {
    "ydsh, version*" {
        exp_continue
    }
    "Copyright*" {
        exp_continue
    }
    "ydsh-*" {
        send "assert(\$1 == 'hello'); exit 0\r"
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
exit $status