#!/usr/bin/env expect

# set argument


set CTRLD \004

set bin_name [lindex $argv 0]
spawn ${bin_name} --quiet --norc -s hello

expect {
    -re "\\$ $" {
        send "assert(\$1 == 'hello'); exit 0\r"
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
exit $status
