#!/usr/bin/env expect

# ctrl-c

set bin_name [lindex $argv 0]
spawn ${bin_name} --quiet --norc

set CTRLD \004
set CTRLC \003

expect {
    -re "\\$ $" {
        send "hello"
        send $CTRLC
    }
    default {
        send_error "mismatch first prompt"
        exit 1
    }
}

expect {
    -re "\\$ $" {
        send $CTRLD
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
exit $status
