#!/usr/bin/env expect

# --norc option

set bin_name [lindex $argv 0]
spawn ${bin_name} --norc

set CTRLD \004

# move home
set CTRL_A \001

# move right
set CTRL_F \006

# move left
set CTRL_B \002

expect {
    -re "\\$ $" {
        send "t"
        send $CTRL_A
        send "$"
        send $CTRL_F
        send "re"
        send $CTRL_B
        send "u\r"
    }
    default {
        send_error "mismatch first prompt"
        exit 1
    }
}

expect {
    "(Boolean) true" {
    }
    default {
        send_error "mismatch"
        exit 1
    }
}

# test multi byte character
expect {
    -re "\\$ $" {
        send "''"
        send $CTRL_F
        send $CTRL_F
        send $CTRL_B
        send "い"
        send $CTRL_B
        send "あ"
        send $CTRL_F
        send "う"
        send $CTRL_B
        send $CTRL_B
        send $CTRL_B
        send $CTRL_B
        send $CTRL_B
        send $CTRL_B
        send "\r"
    }
    default {
        send_error "mismatch first prompt"
        exit 1
    }
}

expect {
    "(String) あいう" {
    }
    default {
        send_error "mismatch"
        exit 1
    }
}

expect {
    -re "\\$ $" {
        send $CTRLD
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
exit $status
