#!/usr/bin/env expect

# --norc option

set bin_name [lindex $argv 0]
spawn ${bin_name} --norc -- -

set CTRLD \004

expect {
    -re "\\$ $" {
        send "12\r"
    }
    default {
        send_error "mismatch first prompt"
        exit 1
    }
}

expect {
    "(Int32) 12" {
    }
    default {
        send_error "mismatch"
        exit 1
    }
}

expect {
    -re "\\$ $" {
        send "assert(test -t 0)\r"
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect {
    -re "\\$ $" {
        send $CTRLD
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
exit $status
