#!/usr/bin/env expect

# terminal after exit command.
#@status: 56

set CTRLD \004

set bin_name [lindex $argv 0]
spawn ${bin_name} --norc --quiet

expect {
    -re "\\$ $" {
        send "function f(\$s : Int, \$a : Any) { echo hello; }; \$TERM_HOOK = \$f; exit 56\r"
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect {
    "hello" {
    }
    default {
        send_error "mismatch"
        exit 1
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
exit $status
