#!/usr/bin/env expect

# throw exception, but not terminate.

set bin_name [lindex $argv 0]
spawn ${bin_name} --norc --quiet

set CTRLD \004

expect {
    -re "\\$ $" {
        send "1 / 0\r"
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect {
    "\[runtime error\]" {
    }
    default {
        send_error "mismatch"
    }
}

expect {
    -re "\\$ $" {
        send $CTRLD
    }
    default {
        send_error "mismatch prompt"
        exit 1
    }
}

expect default
catch wait result
set os_error [ lindex $result 2 ]
if { $os_error == -1 } {
    send_error "execution failed"
    exit 1
}
set status [ lindex $result 3]
if { $status != 0 } {
    send_error "mismatch exit status"
    exit 1
}
exit 0
