#include "gtest/gtest.h"

#include "../tools/test262regex/js_lexer.h"
#include "../tools/test262regex/meta.h"

using namespace arsh;
using namespace arsh::re262;

TEST(MetaDataTest, error) {
  const char *input = "";
  std::string err;
  auto ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("cannot extract meta data section", err);

  err.clear();
  input = "/*---*/";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("cannot extract meta data section", err);

  err.clear();
  input = "/*------*/";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("cannot extract meta data section", err);

  err.clear();
  input = R"(/*---
#
 fhaurf
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized line in meta-data section\nfhaurf", err);

  err.clear();
  input = R"(/*---
hoge: hello world
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: hoge\nhoge: hello world", err);

  err.clear();
  input = R"(/*---
author: [1234]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: author\nauthor: [1234]", err);

  err.clear();
  input = R"(/*---
features: >
[hello]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: features\nfeatures: >", err);

  err.clear();
  input = R"(/*---
includes: |
[hello]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: includes\nincludes: |", err);

  err.clear();
  input = R"(/*---
negative: |
this is
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: negative\nnegative: |", err);

  err.clear();
  input = R"(/*---
negative:
phase: runtime
type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("attribute must start with indent in negative:\nphase: runtime", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtime
type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("attribute must start with indent in negative:\ntype: error", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtime
 phase
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute in negative:\nphase", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtimed
 type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized value in phase: runtimed, must be `parse' or `runtime'", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtime
 Type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute in negative:\nType: error", err);

  err.clear();
  input = R"(/*---
author: my
negative:
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("phase or type are not provided", err);

  err.clear();
  input = R"(/*---
author: my
negative:
  phase: parse
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("phase or type are not provided", err);

  err.clear();
  input = R"(/*---
author: my
negative:
    type: parse error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("phase or type are not provided", err);
}

TEST(MetaDataTest, base) {
  const char *input = R"(// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Changes_When_Casemapped`
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [
   2345,
)";
  auto ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Unicode property escapes for `Changes_When_Casemapped`", ret.value().description);
  ASSERT_EQ("Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests\nUnicode "
            "v17.0.0",
            ret.value().info);
  ASSERT_EQ("sec-static-semantics-unicodematchproperty-p", ret.value().esid);
  ASSERT_EQ(1, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ(1, ret.value().includes.size());
  ASSERT_EQ("regExpUtils.js", ret.value().includes[0]);
  ASSERT_FALSE(ret.value().negative.has_value());

  //
  input = R"(// Copyright 2018 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Binary properties with an explicit value must throw in Unicode property
  escapes (even if the value is valid).
esid: sec-static-semantics-unicodematchproperty-p
negative:
  phase: parse
  type: SyntaxError
features: [regexp-unicode-property-escapes]
---*/

$DONOTEVALUATE();

/\P{ASCII=No}/u;
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Binary properties with an explicit value must throw in Unicode property escapes (even "
            "if the value is valid).",
            ret.value().description);
  ASSERT_EQ("", ret.value().info);
  ASSERT_EQ("sec-static-semantics-unicodematchproperty-p", ret.value().esid);
  ASSERT_EQ(1, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ(0, ret.value().includes.size());
  ASSERT_TRUE(ret.value().negative.has_value());
  ASSERT_EQ(TestMetaData::Phase::PARSE, ret.value().negative.value().phase);
  ASSERT_EQ("SyntaxError", ret.value().negative.value().type);

  //
  input = R"(
// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Negating Unicode property escapes for `RGI_Emoji_ZWJ_Sequence` (property of strings) with `\P{…}` throws an early error.
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-isvalidregularexpressionliteral
features: [regexp-unicode-property-escapes, regexp-v-flag]
negative:
  phase: parse
  type: SyntaxError
---*/

$DONOTEVALUATE();

/\P{RGI_Emoji_ZWJ_Sequence}/v;
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Negating Unicode property escapes for `RGI_Emoji_ZWJ_Sequence` (property of strings) "
            "with `\\P{…}` throws an early error.",
            ret.value().description);
  ASSERT_EQ("Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests\nUnicode "
            "v17.0.0",
            ret.value().info);
  ASSERT_EQ("sec-isvalidregularexpressionliteral", ret.value().esid);
  ASSERT_EQ(2, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ("regexp-v-flag", ret.value().features[1]);
  ASSERT_EQ(0, ret.value().includes.size());
  ASSERT_TRUE(ret.value().negative.has_value());
  ASSERT_EQ(TestMetaData::Phase::PARSE, ret.value().negative.value().phase);
  ASSERT_EQ("SyntaxError", ret.value().negative.value().type);

  //
  input = R"(
// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Extended character classes enabled by the RegExp `v` flag support
  properties of strings, string literals, and set operations
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-patterns
features: [regexp-unicode-property-escapes, regexp-v-flag]
includes: [regExpUtils.js]
---*/

testExtendedCharacterClass({
  regExp: /^[\d--\p{Emoji_Keycap_Sequence}]+$/v,
  expression: "[\d--\p{Emoji_Keycap_Sequence}]",
  matchStrings: [
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Extended character classes enabled by the RegExp `v` flag support properties of "
            "strings, string literals, and set operations",
            ret.value().description);
  ASSERT_EQ("Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests\nUnicode "
            "v17.0.0",
            ret.value().info);
  ASSERT_EQ("sec-patterns", ret.value().esid);
  ASSERT_EQ(2, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ("regexp-v-flag", ret.value().features[1]);
  ASSERT_EQ(1, ret.value().includes.size());
  ASSERT_EQ("regExpUtils.js", ret.value().includes[0]);
  ASSERT_FALSE(ret.value().negative.has_value());

  //
  input = R"(// Copyright 2018 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  NonemptyClassRanges :: ClassAtom - ClassAtom ClassRanges

  It is a Syntax Error if IsCharacterClass of the first ClassAtom is
  true or IsCharacterClass of the second ClassAtom is true.
esid: sec-patterns-static-semantics-early-errors
negative:
  phase: parse
  type: SyntaxError
features: [regexp-unicode-property-escapes]
---*/

$DONOTEVALUATE();

/[--\p{Hex}]/u;
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("NonemptyClassRanges :: ClassAtom - ClassAtom ClassRanges\n"
            "It is a Syntax Error if IsCharacterClass of the first ClassAtom is true or "
            "IsCharacterClass of the second ClassAtom is true.",
            ret.value().description);
  ASSERT_EQ("", ret.value().info);
  ASSERT_EQ("sec-patterns-static-semantics-early-errors", ret.value().esid);
  ASSERT_EQ(1, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ(0, ret.value().includes.size());
  ASSERT_TRUE(ret.value().negative.has_value());
  ASSERT_EQ(TestMetaData::Phase::PARSE, ret.value().negative.value().phase);
  ASSERT_EQ("SyntaxError", ret.value().negative.value().type);
}

std::vector<std::pair<JSTokenKind, std::string>> tokenize(JSLexer &lexer) {
  std::vector<std::pair<JSTokenKind, std::string>> values;
  JSTokenKind kind = JSTokenKind::INVALID;
  do {
    Token token;
    kind = lexer.nextToken(token);
    values.emplace_back(kind, lexer.toTokenText(token));
  } while (kind != JSTokenKind::EOS);
  return values;
}

class JSLexerTest : public ::testing::Test {
public:
  static void checkString(const char *literal, const std::u16string &expected) {
    std::string err;
    auto ret = JSLexer::unquoteString(literal, &err);
    ASSERT_TRUE(ret.has_value());
    ASSERT_TRUE(err.empty());
    ASSERT_EQ(expected, ret.value());
  }

  static void checkStringErr(const char *literal, const std::string &expectedErr) {
    std::string err;
    auto ret = JSLexer::unquoteString(literal, &err);
    ASSERT_FALSE(ret.has_value());
    ASSERT_FALSE(err.empty());
    ASSERT_EQ(expectedErr, err);
  }
};

TEST_F(JSLexerTest, base1) {
  const char *src = R"(// Copyright 2018 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Properties not explicitly listed in the Unicode property escapes spec must
  not be supported.
esid: sec-static-semantics-unicodematchproperty-p
negative:
  phase: parse
  type: SyntaxError
features: [regexp-unicode-property-escapes]
---*/

$DONOTEVALUATE();

/\p{FC_NFKC_Closure}/u;)";
  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::IDENTIFIER, "$DONOTEVALUATE"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::REGEX, "/\\p{FC_NFKC_Closure}/u"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected, values);
}

using TokenList = std::vector<std::pair<JSTokenKind, std::string>>;

static std::pair<TokenList, TokenList> split(const TokenList &list) {
  TokenList sub1;
  TokenList sub2;
  unsigned int half = list.size() / 2;
  for (unsigned int i = 0; i < half; i++) {
    sub1.emplace_back(list[i]);
  }
  for (unsigned int i = half; i < list.size(); i++) {
    sub2.emplace_back(list[i]);
  }
  return {std::move(sub1), std::move(sub2)};
}

TEST_F(JSLexerTest, base2) {
  const char *src = R"E(// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Any`
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [],
  ranges: [
    [0x00DC00, 0x00DFFF],
    [0x00E000, 0x10FFFF]
  ]
});

assert(
  !/\P{Any}/u.test(""),
  "`\\P{Any}` should match nothing (not even the empty string)"
);
)E";

  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::CONST, "const"},
      {JSTokenKind::IDENTIFIER, "matchSymbols"},
      {JSTokenKind::ASSIGN, "="},
      {JSTokenKind::IDENTIFIER, "buildString"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::LBC, "{"},
      {JSTokenKind::IDENTIFIER, "loneCodePoints"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "ranges"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::LB, "["},
      {JSTokenKind::NUMBER, "0x00DC00"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::NUMBER, "0x00DFFF"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::LB, "["},
      {JSTokenKind::NUMBER, "0x00E000"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::NUMBER, "0x10FFFF"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::RBC, "}"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},

      {JSTokenKind::IDENTIFIER, "assert"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::NOT, "!"},
      {JSTokenKind::REGEX, "/\\P{Any}/u"},
      {JSTokenKind::DOT, "."},
      {JSTokenKind::IDENTIFIER, "test"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::STRING, R"E("")E"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::STRING, R"E("`\\P{Any}` should match nothing (not even the empty string)")E"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected.size(), values.size());
  auto [expected1, expected2] = split(expected);
  auto [values1, values2] = split(values);
  ASSERT_EQ(expected1, values1);
  ASSERT_EQ(expected2, values2);
}

TEST_F(JSLexerTest, base3) {
  const char *src = R"E(
/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Basic_Emoji` (property of strings)
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes, regexp-v-flag]
includes: [regExpUtils.js]
---*/

testPropertyOfStrings({
  regExp: /^\p{Basic_Emoji}+$/v,
  expression: "\\p{Basic_Emoji}",
  matchStrings: [
    "\xAE\uFE0F",
    "\u{1F6F3}\uFE0F"
  ],
  nonMatchStrings: [
    "\uFE0F",
    "\xA9",
  ],
});
)E";

  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::IDENTIFIER, "testPropertyOfStrings"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::LBC, "{"},
      {JSTokenKind::IDENTIFIER, "regExp"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::REGEX, R"E(/^\p{Basic_Emoji}+$/v)E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "expression"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::STRING, R"E("\\p{Basic_Emoji}")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "matchStrings"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::STRING, R"E("\xAE\uFE0F")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::STRING, R"E("\u{1F6F3}\uFE0F")E"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "nonMatchStrings"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::STRING, R"E("\uFE0F")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::STRING, R"E("\xA9")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::RBC, "}"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected.size(), values.size());
  auto [expected1, expected2] = split(expected);
  auto [values1, values2] = split(values);
  ASSERT_EQ(expected1, values1);
  ASSERT_EQ(expected2, values2);
}

TEST_F(JSLexerTest, string1) {
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("")E", u""));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("1")E", u"1"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("あ")E", u"あ"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\x40")E", u"@"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\u0150")E", u"Ő"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\u{25E56}")E", u"𥹖"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\n")E", u"\n"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\r")E", u"\r"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\t")E", u"\t"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\f")E", u"\f"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\b")E", u"\b"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\v")E", u"\v"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\"")E", u"\""));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\'")E", u"'"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E('\'')E", u"'"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E('\"')E", u"\""));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E('\\')E", u"\\"));
  ASSERT_NO_FATAL_FAILURE(checkString("\"12\\\n34\"", u"1234"));
  ASSERT_NO_FATAL_FAILURE(checkString("\"12\\\r34\"", u"1234"));
  ASSERT_NO_FATAL_FAILURE(checkString("'12\\\u2028あ'", u"12あ"));
  ASSERT_NO_FATAL_FAILURE(checkString("'12\\\u2029あ'", u"12あ"));
  ASSERT_NO_FATAL_FAILURE(checkString("'\\あ'", u"あ"));
  ASSERT_NO_FATAL_FAILURE(checkString("'\\@'", u"@"));

  {
    auto ret = JSLexer::unquoteString(R"("\0")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(1, ret.value().size());
    ASSERT_EQ('\0', ret.value()[0]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("𠮟")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(2, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
    ASSERT_EQ(0xDF9F, ret.value()[1]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\uD842\uDF9F")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(2, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
    ASSERT_EQ(0xDF9F, ret.value()[1]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\uD842")", nullptr); // lone surrogate
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(1, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\uDF9F")", nullptr); // lone surrogate
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(1, ret.value().size());
    ASSERT_EQ(0xDF9F, ret.value()[0]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\u{20B9F}")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(2, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
    ASSERT_EQ(0xDF9F, ret.value()[1]);
  }
}

TEST_F(JSLexerTest, string2) {
  {
    std::string err;
    JSLexer lex("(dummy)", "this is a pen");
    auto ret = lex.toString(Token{}, &err);
    ASSERT_FALSE(ret.has_value());
    ASSERT_EQ("must be valid string literal", err);
  }

  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\00")E", "octal escape sequence is not allowed: \\0"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\12")E", "octal escape sequence is not allowed: \\1"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\22")E", "octal escape sequence is not allowed: \\2"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\32")E", "octal escape sequence is not allowed: \\3"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\42")E", "octal escape sequence is not allowed: \\4"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\5")E", "octal escape sequence is not allowed: \\5"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\6")E", "octal escape sequence is not allowed: \\6"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\7")E", "octal escape sequence is not allowed: \\7"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\8")E", "\\8 and \\9 escape sequences are not allowed"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\9")E", "\\8 and \\9 escape sequences are not allowed"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\x")E", "broken hex escape sequence: \\x"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\x!")E", "broken hex escape sequence: \\x"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\xD")E", "broken hex escape sequence: \\xD"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\xD@")E", "broken hex escape sequence: \\xD"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u1")E", "broken unicode escape sequence: \\u1"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u12")E", "broken unicode escape sequence: \\u12"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u123")E", "broken unicode escape sequence: \\u123"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u{")E", "unclosed unicode escape sequence: \\u{"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u{}")E", "empty unicode escape sequence: \\u{}"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u{@")E", "broken unicode escape sequence: \\u{"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\u{FF@")E", "broken unicode escape sequence: \\u{FF"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\u{FFFFFF}")E", "out-of-range code point: \\U+FFFFFF"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("12\")E", "broken escape sequence: \\"));
}

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}