#include "../test_common.h"

#include "../tools/test262regex/js_lexer.h"
#include "../tools/test262regex/js_regex.h"
#include "../tools/test262regex/meta.h"

#ifndef BIN_PATH
#error require BIN_PATH
#endif

#ifndef RE262_PATH
#error require RE262_PATH
#endif

#ifndef RE262_TEST_DIR
#error require RE262_TEST_DIR
#endif

#ifndef LITECHECK_PATH
#error require LITECHECK_PATH
#endif

using namespace arsh;
using namespace arsh::re262;

TEST(MetaDataTest, error) {
  const char *input = "";
  std::string err;
  auto ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("cannot extract meta data section", err);

  err.clear();
  input = "/*---*/";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("cannot extract meta data section", err);

  err.clear();
  input = "/*------*/";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("cannot extract meta data section", err);

  err.clear();
  input = R"(/*---
#
 fhaurf
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized line in meta-data section\nfhaurf", err);

  err.clear();
  input = R"(/*---
hoge: hello world
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: hoge\nhoge: hello world", err);

  err.clear();
  input = R"(/*---
author: [1234]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: author\nauthor: [1234]", err);

  err.clear();
  input = R"(/*---
features: >
[hello]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: features\nfeatures: >", err);

  err.clear();
  input = R"(/*---
includes: |
[hello]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: includes\nincludes: |", err);

  err.clear();
  input = R"(/*---
negative: |
this is
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: negative\nnegative: |", err);

  err.clear();
  input = R"(/*---
negative:
phase: runtime
type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("attribute must start with indent in negative:\nphase: runtime", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtime
type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("attribute must start with indent in negative:\ntype: error", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtime
 phase
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute in negative:\nphase", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtimed
 type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized value in phase: runtimed, must be `parse' or `runtime'", err);

  err.clear();
  input = R"(/*---
negative:
 phase: runtime
 Type: error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute in negative:\nType: error", err);

  err.clear();
  input = R"(/*---
author: my
negative:
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("phase or type are not provided", err);

  err.clear();
  input = R"(/*---
author: my
negative:
  phase: parse
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("phase or type are not provided", err);

  err.clear();
  input = R"(/*---
author: my
negative:
    type: parse error
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("phase or type are not provided", err);

  err.clear();
  input = R"(/*---
author: my
flags: 1234
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized attribute: flags\nflags: 1234", err);

  err.clear();
  input = R"(/*---
author: my
flags: [generated, huga]
---*/)";
  ret = TestMetaData::extractFrom(input, &err);
  ASSERT_FALSE(ret.has_value());
  ASSERT_EQ("unrecognized value in flags: huga, must be `onlyStrict', `noStrict' or `generated'",
            err);
}

TEST(MetaDataTest, base) {
  const char *input = R"(// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Changes_When_Casemapped`
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [
   2345,
)";
  auto ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Unicode property escapes for `Changes_When_Casemapped`", ret.value().description);
  ASSERT_EQ("Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests\nUnicode "
            "v17.0.0",
            ret.value().info);
  ASSERT_EQ("sec-static-semantics-unicodematchproperty-p", ret.value().esid);
  ASSERT_EQ(1, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ(1, ret.value().includes.size());
  ASSERT_EQ("regExpUtils.js", ret.value().includes[0]);
  ASSERT_FALSE(ret.value().negative.has_value());

  //
  input = R"(// Copyright 2018 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Binary properties with an explicit value must throw in Unicode property
  escapes (even if the value is valid).
esid: sec-static-semantics-unicodematchproperty-p
negative:
  phase: parse
  type: SyntaxError
features: [regexp-unicode-property-escapes]
---*/

$DONOTEVALUATE();

/\P{ASCII=No}/u;
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Binary properties with an explicit value must throw in Unicode property escapes (even "
            "if the value is valid).",
            ret.value().description);
  ASSERT_EQ("", ret.value().info);
  ASSERT_EQ("sec-static-semantics-unicodematchproperty-p", ret.value().esid);
  ASSERT_EQ(1, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ(0, ret.value().includes.size());
  ASSERT_TRUE(ret.value().negative.has_value());
  ASSERT_EQ(TestMetaData::Phase::PARSE, ret.value().negative.value().phase);
  ASSERT_EQ("SyntaxError", ret.value().negative.value().type);

  //
  input = R"(
// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Negating Unicode property escapes for `RGI_Emoji_ZWJ_Sequence` (property of strings) with `\P{…}` throws an early error.
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-isvalidregularexpressionliteral
features: [regexp-unicode-property-escapes, regexp-v-flag]
negative:
  phase: parse
  type: SyntaxError
---*/

$DONOTEVALUATE();

/\P{RGI_Emoji_ZWJ_Sequence}/v;
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Negating Unicode property escapes for `RGI_Emoji_ZWJ_Sequence` (property of strings) "
            "with `\\P{…}` throws an early error.",
            ret.value().description);
  ASSERT_EQ("Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests\nUnicode "
            "v17.0.0",
            ret.value().info);
  ASSERT_EQ("sec-isvalidregularexpressionliteral", ret.value().esid);
  ASSERT_EQ(2, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ("regexp-v-flag", ret.value().features[1]);
  ASSERT_EQ(0, ret.value().includes.size());
  ASSERT_TRUE(ret.value().negative.has_value());
  ASSERT_EQ(TestMetaData::Phase::PARSE, ret.value().negative.value().phase);
  ASSERT_EQ("SyntaxError", ret.value().negative.value().type);

  //
  input = R"(
// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Extended character classes enabled by the RegExp `v` flag support
  properties of strings, string literals, and set operations
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-patterns
features: [regexp-unicode-property-escapes, regexp-v-flag]
includes: [regExpUtils.js]
---*/

testExtendedCharacterClass({
  regExp: /^[\d--\p{Emoji_Keycap_Sequence}]+$/v,
  expression: "[\d--\p{Emoji_Keycap_Sequence}]",
  matchStrings: [
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("Extended character classes enabled by the RegExp `v` flag support properties of "
            "strings, string literals, and set operations",
            ret.value().description);
  ASSERT_EQ("Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests\nUnicode "
            "v17.0.0",
            ret.value().info);
  ASSERT_EQ("sec-patterns", ret.value().esid);
  ASSERT_EQ(2, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ("regexp-v-flag", ret.value().features[1]);
  ASSERT_EQ(1, ret.value().includes.size());
  ASSERT_EQ("regExpUtils.js", ret.value().includes[0]);
  ASSERT_FALSE(ret.value().negative.has_value());

  //
  input = R"(// Copyright 2018 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  NonemptyClassRanges :: ClassAtom - ClassAtom ClassRanges

  It is a Syntax Error if IsCharacterClass of the first ClassAtom is
  true or IsCharacterClass of the second ClassAtom is true.
esid: sec-patterns-static-semantics-early-errors
negative:
  phase: parse
  type: SyntaxError
features: [regexp-unicode-property-escapes]
---*/

$DONOTEVALUATE();

/[--\p{Hex}]/u;
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("Mathias Bynens", ret.value().author);
  ASSERT_EQ("NonemptyClassRanges :: ClassAtom - ClassAtom ClassRanges\n"
            "It is a Syntax Error if IsCharacterClass of the first ClassAtom is true or "
            "IsCharacterClass of the second ClassAtom is true.",
            ret.value().description);
  ASSERT_EQ("", ret.value().info);
  ASSERT_EQ("sec-patterns-static-semantics-early-errors", ret.value().esid);
  ASSERT_EQ(1, ret.value().features.size());
  ASSERT_EQ("regexp-unicode-property-escapes", ret.value().features[0]);
  ASSERT_EQ(0, ret.value().includes.size());
  ASSERT_TRUE(ret.value().negative.has_value());
  ASSERT_EQ(TestMetaData::Phase::PARSE, ret.value().negative.value().phase);
  ASSERT_EQ("SyntaxError", ret.value().negative.value().type);
}

TEST(MetaDataTest, oldESID) {
  const char *input = R"(
/*---
es5id: 15.10.1_A1_T10
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [
   2345,
)";
  auto ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("15.10.1_A1_T10", ret.value().esid);

  input = R"(
/*---
es6id: 21.1.2
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [
   2345,
)";
  ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("21.1.2", ret.value().esid);
}

TEST(MetaDataTest, flags) {
  const char *input = R"(
/*---
es5id: 15.10.1_A1_T10
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
flags: [generated]
---*/

const matchSymbols = buildString({
  loneCodePoints: [
   2345,
)";
  auto ret = TestMetaData::extractFrom(input, nullptr);
  ASSERT_TRUE(ret.has_value());
  ASSERT_EQ("15.10.1_A1_T10", ret.value().esid);
  ASSERT_TRUE(hasFlag(ret.value().flags, TestMetaData::Flag::GENERATED));
}

std::vector<std::pair<JSTokenKind, std::string>> tokenize(JSLexer &lexer) {
  std::vector<std::pair<JSTokenKind, std::string>> values;
  JSTokenKind kind = JSTokenKind::INVALID;
  do {
    Token token;
    kind = lexer.nextToken(token);
    values.emplace_back(kind, lexer.toTokenText(token));
  } while (kind != JSTokenKind::EOS);
  return values;
}

class JSLexerTest : public ::testing::Test {
public:
  static void checkString(const char *literal, const std::u16string &expected) {
    std::string err;
    auto ret = JSLexer::unquoteString(literal, &err);
    ASSERT_TRUE(ret.has_value());
    ASSERT_TRUE(err.empty());
    ASSERT_EQ(expected, ret.value());
  }

  static void checkStringErr(const char *literal, const std::string &expectedErr) {
    std::string err;
    auto ret = JSLexer::unquoteString(literal, &err);
    ASSERT_FALSE(ret.has_value());
    ASSERT_FALSE(err.empty());
    ASSERT_EQ(expectedErr, err);
  }
};

TEST_F(JSLexerTest, base1) {
  const char *src = R"(// Copyright 2018 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Properties not explicitly listed in the Unicode property escapes spec must
  not be supported.
esid: sec-static-semantics-unicodematchproperty-p
negative:
  phase: parse
  type: SyntaxError
features: [regexp-unicode-property-escapes]
---*/

$DONOTEVALUATE();

/\p{FC_NFKC_Closure}/u;)";
  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::IDENTIFIER, "$DONOTEVALUATE"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::REGEX, "/\\p{FC_NFKC_Closure}/u"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected, values);
}

using TokenList = std::vector<std::pair<JSTokenKind, std::string>>;

static std::pair<TokenList, TokenList> split(const TokenList &list) {
  TokenList sub1;
  TokenList sub2;
  unsigned int half = list.size() / 2;
  for (unsigned int i = 0; i < half; i++) {
    sub1.emplace_back(list[i]);
  }
  for (unsigned int i = half; i < list.size(); i++) {
    sub2.emplace_back(list[i]);
  }
  return {std::move(sub1), std::move(sub2)};
}

TEST_F(JSLexerTest, base2) {
  const char *src = R"E(// Copyright 2025 Mathias Bynens. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.

/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Any`
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes]
includes: [regExpUtils.js]
---*/

const matchSymbols = buildString({
  loneCodePoints: [],
  ranges: [
    [0x00DC00, 0x00DFFF],
    [0x00E000, 0x10FFFF]
  ]
});

assert(
  !/\P{Any}/u.test(""),
  "`\\P{Any}` should match nothing (not even the empty string)"
);
)E";

  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::CONST, "const"},
      {JSTokenKind::IDENTIFIER, "matchSymbols"},
      {JSTokenKind::ASSIGN, "="},
      {JSTokenKind::IDENTIFIER, "buildString"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::LBC, "{"},
      {JSTokenKind::IDENTIFIER, "loneCodePoints"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "ranges"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::LB, "["},
      {JSTokenKind::NUMBER, "0x00DC00"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::NUMBER, "0x00DFFF"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::LB, "["},
      {JSTokenKind::NUMBER, "0x00E000"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::NUMBER, "0x10FFFF"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::RBC, "}"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},

      {JSTokenKind::IDENTIFIER, "assert"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::NOT, "!"},
      {JSTokenKind::REGEX, "/\\P{Any}/u"},
      {JSTokenKind::DOT, "."},
      {JSTokenKind::IDENTIFIER, "test"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::STRING, R"E("")E"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::STRING, R"E("`\\P{Any}` should match nothing (not even the empty string)")E"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected.size(), values.size());
  auto [expected1, expected2] = split(expected);
  auto [values1, values2] = split(values);
  ASSERT_EQ(expected1, values1);
  ASSERT_EQ(expected2, values2);
}

TEST_F(JSLexerTest, base3) {
  const char *src = R"E(
/*---
author: Mathias Bynens
description: >
  Unicode property escapes for `Basic_Emoji` (property of strings)
info: |
  Generated by https://github.com/mathiasbynens/unicode-property-escapes-tests
  Unicode v17.0.0
esid: sec-static-semantics-unicodematchproperty-p
features: [regexp-unicode-property-escapes, regexp-v-flag]
includes: [regExpUtils.js]
---*/

testPropertyOfStrings({
  regExp: /^\p{Basic_Emoji}+$/v,
  expression: "\\p{Basic_Emoji}",
  matchStrings: [
    "\xAE\uFE0F",
    "\u{1F6F3}\uFE0F"
  ],
  nonMatchStrings: [
    "\uFE0F",
    "\xA9",
  ],
});
)E";

  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::IDENTIFIER, "testPropertyOfStrings"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::LBC, "{"},
      {JSTokenKind::IDENTIFIER, "regExp"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::REGEX, R"E(/^\p{Basic_Emoji}+$/v)E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "expression"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::STRING, R"E("\\p{Basic_Emoji}")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "matchStrings"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::STRING, R"E("\xAE\uFE0F")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::STRING, R"E("\u{1F6F3}\uFE0F")E"},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::IDENTIFIER, "nonMatchStrings"},
      {JSTokenKind::COLON, ":"},
      {JSTokenKind::LB, "["},
      {JSTokenKind::STRING, R"E("\uFE0F")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::STRING, R"E("\xA9")E"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::RB, "]"},
      {JSTokenKind::COMMA, ","},
      {JSTokenKind::RBC, "}"},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected.size(), values.size());
  auto [expected1, expected2] = split(expected);
  auto [values1, values2] = split(values);
  ASSERT_EQ(expected1, values1);
  ASSERT_EQ(expected2, values2);
}

TEST_F(JSLexerTest, comment) {
  const char *src = R"E(
/*---
this is a comment1
---*/

$DONOTEVALUATE();

/**/

/*
this is a comment2
*/
12;
// this is a comment3
34;
)E";

  JSLexer lexer("(source)", src);
  auto values = tokenize(lexer);
  std::vector<std::pair<JSTokenKind, std::string>> expected = {
      {JSTokenKind::IDENTIFIER, "$DONOTEVALUATE"},
      {JSTokenKind::LP, "("},
      {JSTokenKind::RP, ")"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::NUMBER, "12"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::NUMBER, "34"},
      {JSTokenKind::LINE_END, ";"},
      {JSTokenKind::EOS, ""},
  };
  ASSERT_EQ(expected, values);
}

TEST_F(JSLexerTest, string1) {
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("")E", u""));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("1")E", u"1"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("あ")E", u"あ"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\x40")E", u"@"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\u0150")E", u"Ő"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\u{25E56}")E", u"𥹖"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\n")E", u"\n"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\r")E", u"\r"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\t")E", u"\t"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\f")E", u"\f"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\b")E", u"\b"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\v")E", u"\v"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\"")E", u"\""));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E("\'")E", u"'"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E('\'')E", u"'"));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E('\"')E", u"\""));
  ASSERT_NO_FATAL_FAILURE(checkString(R"E('\\')E", u"\\"));
  ASSERT_NO_FATAL_FAILURE(checkString("\"12\\\n34\"", u"1234"));
  ASSERT_NO_FATAL_FAILURE(checkString("\"12\\\r34\"", u"1234"));
  ASSERT_NO_FATAL_FAILURE(checkString("'12\\\u2028あ'", u"12あ"));
  ASSERT_NO_FATAL_FAILURE(checkString("'12\\\u2029あ'", u"12あ"));
  ASSERT_NO_FATAL_FAILURE(checkString("'\\あ'", u"あ"));
  ASSERT_NO_FATAL_FAILURE(checkString("'\\@'", u"@"));

  {
    auto ret = JSLexer::unquoteString(R"("\0")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(1, ret.value().size());
    ASSERT_EQ('\0', ret.value()[0]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("𠮟")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(2, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
    ASSERT_EQ(0xDF9F, ret.value()[1]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\uD842\uDF9F")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(2, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
    ASSERT_EQ(0xDF9F, ret.value()[1]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\uD842")", nullptr); // lone surrogate
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(1, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\uDF9F")", nullptr); // lone surrogate
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(1, ret.value().size());
    ASSERT_EQ(0xDF9F, ret.value()[0]);
  }

  {
    auto ret = JSLexer::unquoteString(R"("\u{20B9F}")", nullptr);
    ASSERT_TRUE(ret.has_value());
    ASSERT_EQ(2, ret.value().size());
    ASSERT_EQ(0xD842, ret.value()[0]);
    ASSERT_EQ(0xDF9F, ret.value()[1]);
  }
}

TEST_F(JSLexerTest, string2) {
  {
    std::string err;
    JSLexer lex("(dummy)", "this is a pen");
    auto ret = lex.toString(Token{}, &err);
    ASSERT_FALSE(ret.has_value());
    ASSERT_EQ("must be valid string literal", err);
  }

  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\00")E", "octal escape sequence is not allowed: \\0"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\12")E", "octal escape sequence is not allowed: \\1"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\22")E", "octal escape sequence is not allowed: \\2"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\32")E", "octal escape sequence is not allowed: \\3"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\42")E", "octal escape sequence is not allowed: \\4"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\5")E", "octal escape sequence is not allowed: \\5"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\6")E", "octal escape sequence is not allowed: \\6"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\7")E", "octal escape sequence is not allowed: \\7"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\8")E", "\\8 and \\9 escape sequences are not allowed"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\9")E", "\\8 and \\9 escape sequences are not allowed"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\x")E", "broken hex escape sequence: \\x"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\x!")E", "broken hex escape sequence: \\x"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\xD")E", "broken hex escape sequence: \\xD"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\xD@")E", "broken hex escape sequence: \\xD"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u1")E", "broken unicode escape sequence: \\u1"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u12")E", "broken unicode escape sequence: \\u12"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u123")E", "broken unicode escape sequence: \\u123"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u{")E", "unclosed unicode escape sequence: \\u{"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u{}")E", "empty unicode escape sequence: \\u{}"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("\u{@")E", "broken unicode escape sequence: \\u{"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\u{FF@")E", "broken unicode escape sequence: \\u{FF"));
  ASSERT_NO_FATAL_FAILURE(
      checkStringErr(R"E("\u{FFFFFF}")E", "out-of-range code point: \\U+FFFFFF"));
  ASSERT_NO_FATAL_FAILURE(checkStringErr(R"E("12\")E", "broken escape sequence: \\"));
}

TEST(JSRegexTest, literal) {
  auto env = initJSEnv();
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "", &err);
    ASSERT_FALSE(ret);
    ASSERT_EQ("invalid regular expression literal", err);
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "dd", &err);
    ASSERT_FALSE(ret);
    ASSERT_EQ("invalid regular expression literal", err);
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/dd", &err);
    ASSERT_FALSE(ret);
    ASSERT_EQ("invalid regular expression literal", err);
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/dd/@", &err);
    ASSERT_FALSE(ret);
    ASSERT_EQ("invalid regular expression flags", err);
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/dd/iysugdm", &err);
    ASSERT_TRUE(ret);
    ASSERT_EQ("", err);
    ASSERT_EQ(u"/dd/dgimsuy", toPrettyString(ret));
  }
}

TEST(JSRegexTest, exec) {
  auto env = initJSEnv();
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/ABC/i", &err);
    ASSERT_TRUE(ret);
    ASSERT_EQ("", err);
    auto obj = execJSRegex(*ret, newJSString("123"));
    ASSERT_TRUE(obj.has_value());
    ASSERT_FALSE(obj.value());
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/ABC/i", &err);
    ASSERT_TRUE(ret);
    ASSERT_EQ("", err);
    auto obj = execJSRegex(*ret, newJSString("aBc"));
    ASSERT_TRUE(obj.has_value());
    ASSERT_TRUE(obj.value());
    ASSERT_EQ(u"[ aBc, groups: undefined, index: 0, input: aBc ]", toPrettyString(obj.value()));
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/ABC/di", &err);
    ASSERT_TRUE(ret);
    ASSERT_EQ("", err);
    auto obj = execJSRegex(*ret, newJSString("aBc"));
    ASSERT_TRUE(obj.has_value());
    ASSERT_TRUE(obj.value());
    ASSERT_EQ(u"[ aBc, groups: undefined, index: 0, indices: [ [ 0, 3 ], groups: undefined ], "
              "input: aBc ]",
              toPrettyString(obj.value()));
  }

  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/(?<first>.)(?<second>.)/", &err);
    ASSERT_TRUE(ret);
    ASSERT_EQ("", err);
    auto obj = execJSRegex(*ret, newJSString("aあ12b"));
    ASSERT_TRUE(obj.has_value());
    ASSERT_TRUE(obj.value());
    ASSERT_EQ(u"[ aあ, a, あ, groups: { first: a, second: あ }, index: 0, input: aあ12b ]",
              toPrettyString(obj.value()));
  }
  {
    std::string err;
    auto ret = createJSRegexFromLiteral(nullptr, "/(?<first>.)(?<second>.)/d", &err);
    ASSERT_TRUE(ret);
    ASSERT_EQ("", err);
    auto obj = execJSRegex(*ret, newJSString("aあ12b"));
    ASSERT_TRUE(obj.has_value());
    ASSERT_TRUE(obj.value());
    ASSERT_EQ(u"[ aあ, a, あ, groups: { first: a, second: あ }, index: 0, indices: [ [ "
              "0, 2 ], [ 0, 1 ], [ 1, 2 ], groups: { first: [ 0, 1 ], second: [ 1, 2 ] } ], "
              "input: aあ12b ]",
              toPrettyString(obj.value()));
  }
}

TEST(JSTest, syntaxError) {
  {
    std::string err;
    auto ret = jsEval("dummy", "hoge(23", nullptr, false, &err);
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: SyntaxError }, fileName: dummy, "
              "lineNumber: 1, message: "
              "expected `,', `)' }",
              toPrettyString(ret.value));
    const char *expect = R"(dummy:1 [error] expected `,', `)'
hoge(23
       ^
)";
    ASSERT_EQ(expect, err);
  }
  {
    auto ret = jsEval("dummy", "hoge\n(23");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: SyntaxError }, fileName: dummy, "
              "lineNumber: 2, message: "
              "expected `,', `)' }",
              toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "hoge;\n/\\p{ACII}/u");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: SyntaxError }, fileName: dummy, "
              "lineNumber: 2, message: "
              "unrecognized property value: ACII }",
              toPrettyString(ret.value));
  }
}

TEST(JSTest, literal1) {
  {
    auto ret = jsEval("dummy", "null;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<std::nullptr_t>(ret.value));
    ASSERT_EQ(u"null", toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "true;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
    ASSERT_EQ(u"true", toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "false;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_FALSE(std::get<bool>(ret.value));
    ASSERT_EQ(u"false", toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "123;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<double>(ret.value));
    ASSERT_EQ(123, std::get<double>(ret.value));
    ASSERT_EQ(u"123", toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "123.0;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<double>(ret.value));
    ASSERT_EQ(123.0, std::get<double>(ret.value));
    ASSERT_EQ(u"123", toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "3.14;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<double>(ret.value));
    ASSERT_EQ(3.14, std::get<double>(ret.value));
    ASSERT_EQ(toUTF16(std::to_string(3.14)), toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "0xFE12;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<double>(ret.value));
    ASSERT_EQ(0xFE12, std::get<double>(ret.value));
    ASSERT_EQ(toUTF16(std::to_string(0xFE12)), toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "'12ÿþあ𤅕い';");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSStringPtr>(ret.value));
    ASSERT_EQ(u"12ÿþあ𤅕い", *std::get<JSStringPtr>(ret.value));
    ASSERT_EQ(u"12ÿþあ𤅕い", toPrettyString(ret.value));
  }
}

TEST(JSTest, literal2) {
  {
    auto ret = jsEval("dummy", "[123,false,null,[],['s']];");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSArrayPtr>(ret.value));
    ASSERT_EQ(u"[ 123, false, null, [], [ s ] ]", toPrettyString(ret.value));
    ASSERT_EQ(u"123,false,,,s", toString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "{we:false, aa:null, r:{}};");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ aa: null, r: {}, we: false }", toPrettyString(ret.value));
    ASSERT_EQ(u"[object Object]", toString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "/1234/sg;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSRegexPtr>(ret.value));
    ASSERT_EQ(u"/1234/gs", toPrettyString(ret.value));
  }
}

TEST(JSTest, nameRef) {
  {
    auto ret = jsEval("dummy", "undefined;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(isUndefined(ret.value));
    ASSERT_EQ(u"undefined", toPrettyString(ret.value));
    ASSERT_EQ(u"", toString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSFunctionPtr>(ret.value));
    ASSERT_EQ(u"[Function: RegExp]", toPrettyString(ret.value));
    ASSERT_EQ(u"function RegExp() { [native code] }", toString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "SyntaxError;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSFunctionPtr>(ret.value));
    ASSERT_EQ(u"[Function: SyntaxError]", toPrettyString(ret.value));
    ASSERT_EQ(u"function SyntaxError() { [native code] }", toString(ret.value));
  }
}

TEST(JSTest, nameError) {
  auto ret = jsEval("dummy", "hoge;");
  ASSERT_FALSE(ret);
  ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
  ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: ReferenceError }, fileName: dummy, "
            "lineNumber: 1, "
            "message: hoge is not defined }",
            toPrettyString(ret.value));
}

TEST(JSTest, funcCall) {
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSRegexPtr>(ret.value));
    ASSERT_EQ(u"/12/dgsy", toPrettyString(ret.value));
  }
}

TEST(JSTest, funcCallError) {
  {
    auto ret = jsEval("dummy", "undefined();");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy, "
              "lineNumber: 1, "
              "message: not a function }",
              toPrettyString(ret.value));
  }
}

TEST(JSTest, field) {
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').test;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSFunctionPtr>(ret.value));
    ASSERT_EQ(u"[Function: test]", toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').dotAll;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_EQ(u"true", toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').unicode;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_EQ(u"false", toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').fjeria;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(isUndefined(ret.value));
    ASSERT_EQ(u"undefined", toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp.prototype;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ exec: [Function: exec], test: [Function: test] }", toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp.prototype.test;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSFunctionPtr>(ret.value));
    ASSERT_EQ(u"[Function: test]", toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "{qq:23, ss:false,}.qq;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<double>(ret.value));
    ASSERT_EQ(u"23", toPrettyString(ret.value));
  }
}

TEST(JSTest, fieldError) {
  {
    auto ret = jsEval("dummy", "null.hoge;");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy, "
              "lineNumber: 1, "
              "message: Cannot read properties of null (reading 'hoge') }",
              toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy2", "\n\nundefined.test;");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy2, "
              "lineNumber: 3, "
              "message: Cannot read properties of undefined (reading 'test') }",
              toPrettyString(ret.value));
  }
}

TEST(JSTest, methodCall) {
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').test('12');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').test('ww');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_FALSE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12').test('\\uD800');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_FALSE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('\\uD800').test('12\\uD800');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy1", "12;\nRegExp('12').exec('\\uDC00');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(isNull(ret.value));
  }
  {
    auto ret = jsEval("dummy1", "12;\nRegExp('\\uDC00').exec('@\\uDC00');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSArrayPtr>(ret.value));
    ASSERT_EQ(toUTF16("[ \xED\xB0\x80, groups: undefined, index: 1, input: "
                      "@\xED\xB0\x80 ]"),
              toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').exec('ww');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<std::nullptr_t>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').exec('12');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSArrayPtr>(ret.value));
    ASSERT_EQ(u"[ 12, groups: undefined, index: 0, indices: [ [ 0, 2 ], groups: undefined ], "
              "input: 12 ]",
              toPrettyString(ret.value));
  }
}

TEST(JSTest, methodCallError) {
  {
    auto ret = jsEval("dummy", "RegExp('12', 'ysgd').fjeria();");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy, "
              "lineNumber: 1, "
              "message: not a function }",
              toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp.prototype.test('12');");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy, "
              "lineNumber: 1, "
              "message: Method RegExp.prototype.test called on incompatible receiver }",
              toPrettyString(ret.value));
  }
  {
    auto ret = jsEval("dummy", "RegExp.prototype.exec('12');");
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy, "
              "lineNumber: 1, "
              "message: Method RegExp.prototype.exec called on incompatible receiver }",
              toPrettyString(ret.value));
  }
}

TEST(JSTest, proto) {
  {
    auto ret = jsEval("dummy", "/23/.__proto__;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ exec: [Function: exec], test: [Function: test] }", toPrettyString(ret.value));
  }

  {
    auto ret = jsEval("dummy", "SyntaxError().__proto__;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { name: Error }, name: SyntaxError }", toPrettyString(ret.value));
  }
}

TEST(JSTest, unaryOp) {
  {
    auto ret = jsEval("dummy", "!null;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "!undefined;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "!0.0;");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "!'';");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "!!'';");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_FALSE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "!'234';");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_FALSE(std::get<bool>(ret.value));
  }
  {
    auto ret = jsEval("dummy", "!RegExp('12', 'ysgd').test('ww');");
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<bool>(ret.value));
    ASSERT_TRUE(std::get<bool>(ret.value));
  }
}

TEST(JSTest, varDecl) {
  {
    auto env = initJSEnv();
    auto ret = jsEval("dummy", "const DDD = 1234;", env);
    ASSERT_TRUE(ret);
    ASSERT_TRUE(isUndefined(ret.value));
    ret = jsEval("dummy", "DDD;", env);
    ASSERT_TRUE(ret);
    ASSERT_TRUE(std::holds_alternative<double>(ret.value));
    ASSERT_EQ(1234, std::get<double>(ret.value));
  }
  {
    auto env = initJSEnv();
    auto ret = jsEval("dummy", "const DDD = RegExp;", env);
    ASSERT_TRUE(ret);
    ASSERT_TRUE(isUndefined(ret.value));

    ret = jsEval("dummy", "DDD;", env);
    ASSERT_TRUE(ret);
    ASSERT_EQ(u"[Function: RegExp]", toPrettyString(ret.value));

    ret = jsEval("dummy", "(DDD('aa'));", env);
    ASSERT_TRUE(ret);
    ASSERT_EQ(u"/aa/", toPrettyString(ret.value));

    ret = jsEval("dummy", "(DDD)('aa', 'e');", env);
    ASSERT_FALSE(ret);
    ASSERT_TRUE(std::holds_alternative<JSObjectPtr>(ret.value));
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: SyntaxError }, fileName: dummy, "
              "lineNumber: 1, "
              "message: invalid regular expression flags }",
              toPrettyString(ret.value));

    ret = jsEval("dummy2", "const DDD = null;", env);
    ASSERT_FALSE(ret);
    ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy2, "
              "lineNumber: 1, "
              "message: 'DDD' is already defined }",
              toPrettyString(ret.value));
  }
}

TEST(JSTest, instanceOf) {
  auto env = initJSEnv();
  std::string err;
  auto ret = jsEval("dummy2", "const undefined = null;", env, false, &err);
  ASSERT_FALSE(ret);
  ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy2, "
            "lineNumber: 1, "
            "message: 'undefined' is already defined }",
            toPrettyString(ret.value));
  ASSERT_EQ("", err);

  auto ret2 = isInstanceOf(env, 0, ret.value, env->findOrUndef(builtin::TYPE_ERROR));
  ASSERT_TRUE(ret2);
  ASSERT_TRUE(std::get<bool>(ret2.value));

  ret2 = isInstanceOf(env, 0, ret.value, env->findOrUndef(builtin::ERROR));
  ASSERT_TRUE(ret2);
  ASSERT_TRUE(std::get<bool>(ret2.value));

  ret2 = isInstanceOf(env, 0, ret.value, env->findOrUndef(builtin::SYNTAX_ERROR));
  ASSERT_TRUE(ret2);
  ASSERT_FALSE(std::get<bool>(ret2.value));
}

TEST(JSTest, newObject) {
  auto env = initJSEnv();
  auto ret = jsEval("dummy2", "new SyntaxError('hey');", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: SyntaxError }, fileName: dummy2, "
            "lineNumber: 1, "
            "message: hey }",
            toPrettyString(ret.value));

  ret = jsEval("dummy2", "new RegExp('hey', 'v');", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"/hey/v", toPrettyString(ret.value));

  ret = jsEval("dummy2", "new RegExp();", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"/(?:)/", toPrettyString(ret.value));

  ret = jsEval("dummy2", "new RegExp(/1234/i, 'vm');", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"/1234/mv", toPrettyString(ret.value));
}

TEST(JSTest, function) {
  auto env = initJSEnv();
  auto ret = jsEval("dummy1", "let f = function(re, ss) { return re.test(ss); };", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"undefined", toPrettyString(ret.value));

  ret = jsEval("dummy1", "f(/./, '1234');", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ("true", formatEvalResult(env, ret));
}

TEST(JSTest, error) {
  auto env = initJSEnv();
  std::string err;
  auto ret = jsEval("dummy1", "TypeError();", env, false, &err);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: TypeError }, fileName: dummy1, "
            "lineNumber: 1, "
            "message:  }",
            toPrettyString(ret.value));
  ASSERT_EQ("", err);

  ret = jsEval("dummy2", "\nSyntaxError('failed');", env, false, &err);
  ASSERT_TRUE(ret);
  ASSERT_EQ(u"{ __proto__: { __proto__: { name: Error }, name: SyntaxError }, fileName: dummy2, "
            "lineNumber: 2, "
            "message: failed }",
            toPrettyString(ret.value));
  ASSERT_EQ("", err);
}

TEST(JSTest, evalResult) {
  auto env = initJSEnv();
  auto ret = jsEval("dummy1", "12;", env);
  ASSERT_TRUE(ret);
  auto out = formatEvalResult(env, ret);
  ASSERT_EQ("12", out);

  ret = jsEval("dummy2", "hogehoge;", env);
  ASSERT_FALSE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
ReferenceError: hogehoge is not defined
    at dummy2:1)",
            out);
}

TEST(JSTest, toNumber) {
  double d = toNumber(JSValue());
  ASSERT_TRUE(std::isnan(d));
  d = toNumber(static_cast<double>(1234));
  ASSERT_EQ(1234, d);
  d = toNumber(true);
  ASSERT_EQ(1, d);
  d = toNumber(false);
  ASSERT_EQ(0, d);
  d = toNumber(nullptr);
  ASSERT_EQ(0, d);
  d = toNumber(newJSString(""));
  ASSERT_EQ(0, d);
  d = toNumber(newJSString("3.14"));
  ASSERT_EQ(3.14, d);
  d = toNumber(newJSString("-3.14"));
  ASSERT_EQ(-3.14, d);
  d = toNumber(newJSString("fakroi"));
  ASSERT_TRUE(std::isnan(d));
}

TEST(JSTest, harness1) {
  auto env = initJSEnv();
  includeHarness(env);

  auto ret = jsEval("dummy1", "assert(true, 'hey');", env);
  ASSERT_TRUE(ret);
  auto out = formatEvalResult(env, ret);
  ASSERT_EQ("undefined", out);

  ret = jsEval("dummy1", "\nassert(false, 'hey');", env);
  ASSERT_FALSE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: hey
    at dummy1:2)",
            out);

  ret = jsEval("dummy1", "\n\nassert(1234);", env);
  ASSERT_FALSE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: Expected true but got 1234
    at dummy1:3)",
            out);

  ret = jsEval("dummy1", "let g = function(re, ss) { assert(re.test(ss)); 23;};", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ("undefined", formatEvalResult(env, ret));

  ret = jsEval("dummy1", "g(/\\w/, 'w');", env);
  ASSERT_TRUE(ret);
  ASSERT_EQ("undefined", formatEvalResult(env, ret));

  ret = jsEval("dummy1", "g(/\\w/, '@');", env);
  ASSERT_FALSE(ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: Expected true but got false
    at dummy1:1)",
            formatEvalResult(env, ret));
}

TEST(JSTest, harness2) {
  auto env = initJSEnv();
  includeHarness(env);

  auto ret = jsEval("dummy1", "assert.sameValue(true, 'hey');", env);
  ASSERT_FALSE(ret);
  auto out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: Expected SameValue(«true», «hey») to be true
    at dummy1:1)",
            out);

  ret = jsEval("dummy1", "assert.sameValue(true, 'hey', 'failed');", env);
  ASSERT_FALSE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: failed Expected SameValue(«true», «hey») to be true
    at dummy1:1)",
            out);

  ret = jsEval("dummy1", "assert.sameValue(true, /./.test('s'));", env);
  ASSERT_TRUE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ("undefined", out);
}

TEST(JSTest, harness3) {
  auto env = initJSEnv();
  includeHarness(env);

  auto ret = jsEval("dummy1", "assert.notSameValue(12.0, 12);", env);
  ASSERT_FALSE(ret);
  auto out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: Expected SameValue(«12», «12») to be false
    at dummy1:1)",
            out);

  ret = jsEval("dummy1", "assert.notSameValue('hey', 'hey', 'failed');", env);
  ASSERT_FALSE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: failed Expected SameValue(«hey», «hey») to be false
    at dummy1:1)",
            out);

  ret = jsEval("dummy1", "assert.notSameValue(1234, /./.test('s'));", env);
  ASSERT_TRUE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ("undefined", out);
}

TEST(JSTest, harness4) {
  auto env = initJSEnv();
  includeHarness(env);

  auto ret = jsEval("dummy1", "\n\n$DONOTEVALUATE();", env);
  ASSERT_FALSE(ret);
  auto out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: Test262: This statement should not be evaluate
    at dummy1:3)",
            out);
}

TEST(JSTest, harness5) {
  auto env = initJSEnv();
  includeHarness(env);

  auto ret = jsEval("dummy1",
                    "assert.throws(TypeError, function() { $DONOTEVALUATE(); }, 'failed');", env);
  ASSERT_FALSE(ret);
  auto out = formatEvalResult(env, ret);
  ASSERT_EQ(R"([uncaught]
Test262Error: failed Expected a TypeError but got a [object Object]
    at dummy1:1)",
            out);

  ret = jsEval("dummy1", "assert.throws(Test262Error, function() { $DONOTEVALUATE(); }, 'failed');",
               env);
  ASSERT_TRUE(ret);
  out = formatEvalResult(env, ret);
  ASSERT_EQ("undefined", out);
}

static std::vector<std::string> getTargetTestCases(const char *dir) {
  auto ret = getFileList(dir, true);
  assert(!ret.empty());
  ret.erase(std::remove_if(ret.begin(), ret.end(),
                           [](const std::string &v) { return !StringRef(v).endsWith(".js"); }),
            ret.end());
  std::sort(ret.begin(), ret.end());
  return ret;
}

struct Re262Test : ::testing::TestWithParam<std::string> {
  static void doTest() {
    const char *scriptName = GetParam().c_str();
    ProcBuilder builder = {BIN_PATH, LITECHECK_PATH, "-p", "//", "-b", RE262_PATH, scriptName};
    auto result = builder.exec();
    ASSERT_EQ(WaitStatus::EXITED, result.kind);
    if (result.value == 125) {
      printf("  [skip] %s\n", scriptName);
    } else {
      ASSERT_EQ(0, result.value);
    }
  }
};

TEST_P(Re262Test, base) {
  printf(" case: %s\n", this->GetParam().c_str());
  ASSERT_NO_FATAL_FAILURE(doTest());
}

INSTANTIATE_TEST_SUITE_P(Re262Test, Re262Test,
                         ::testing::ValuesIn(getTargetTestCases(RE262_TEST_DIR)));

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}