name: "Emscripten"

on:
  push:
    branches: [ master, ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: emscripten build target
        uses: ./tools/dockerfiles/emsdk
