name: "Emscripten"

on:
  push:
    branches: [ master, ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: emscripten build target
        uses: ./tools/dockerfiles/emsdk
